const diseases = [
    "diabetes", "hypertension", "asthma", "arthritis", "migraine",
    "influenza", "covid-19", "pneumonia", "bronchitis", "anemia",
    "depression", "anxiety", "eczema", "psoriasis", "osteoporosis",
    "tuberculosis", "hepatitis", "malaria", "dengue", "thyroid disorder",
    "sinusitis", "ulcer", "gastritis", "heart disease", "stroke",
    "epilepsy", "cancer", "kidney disease", "liver disease", "insomnia",
    "alzheimer's disease", "parkinson's disease", "multiple sclerosis", "lupus",
    "fibromyalgia", "chronic fatigue syndrome", "irritable bowel syndrome",
    "crohn's disease", "ulcerative colitis", "celiac disease", "endometriosis",
    "polycystic ovary syndrome", "rheumatoid arthritis", "gout", "osteopenia",
    "lyme disease", "chickenpox", "measles", "mumps", "rubella", "whooping cough",
    "tetanus", "diphtheria", "pertussis", "meningitis", "encephalitis",
    "schizophrenia", "bipolar disorder", "obsessive-compulsive disorder",
    "post-traumatic stress disorder", "attention deficit hyperactivity disorder",
    "autism spectrum disorder", "down syndrome", "cerebral palsy", "sickle cell anemia",
    "thalassemia", "hemophilia", "leukemia", "lymphoma", "melanoma", "basal cell carcinoma",
    "squamous cell carcinoma", "pancreatic cancer", "prostate cancer", "breast cancer",
    "ovarian cancer", "cervical cancer", "testicular cancer", "bladder cancer",
    "colorectal cancer", "stomach cancer", "esophageal cancer", "laryngeal cancer",
    "thyroid cancer", "brain tumor", "neurofibromatosis", "tuberous sclerosis",
    "cystic fibrosis", "muscular dystrophy", "myasthenia gravis", "guillain-barre syndrome",
    "amyotrophic lateral sclerosis", "huntington's disease", "wilson's disease",
    "hemochromatosis", "addison's disease", "cushing's syndrome", "hashimoto's thyroiditis",
    "graves' disease", "pituitary tumor", "acromegaly", "diabetes insipidus",
    "hypoglycemia", "hyperthyroidism", "hypothyroidism", "hyperparathyroidism",
    "hypoparathyroidism", "osteomalacia", "rickets", "scurvy", "beriberi", "pellagra",
    "kwashiorkor", "marasmus", "anorexia nervosa", "bulimia nervosa", "binge eating disorder",
    "alcoholism", "substance abuse", "opioid addiction", "nicotine dependence",
    "chronic obstructive pulmonary disease", "emphysema", "pulmonary fibrosis",
    "sarcoidosis", "pulmonary embolism", "pleurisy", "pulmonary hypertension",
    "interstitial lung disease", "bronchiectasis", "cystic fibrosis", "sleep apnea",
    "narcolepsy", "restless legs syndrome", "periodic limb movement disorder",
    "bruxism", "night terrors", "sleepwalking", "circadian rhythm sleep disorder",
    "jet lag", "shift work sleep disorder", "chronic kidney disease", "acute kidney injury",
    "nephrotic syndrome", "glomerulonephritis", "polycystic kidney disease",
    "kidney stones", "urinary tract infection", "pyelonephritis", "cystitis",
    "urethritis", "prostatitis", "benign prostatic hyperplasia", "erectile dysfunction",
    "premature ejaculation", "infertility", "endometriosis", "uterine fibroids",
    "pelvic inflammatory disease", "menopause", "premenstrual syndrome",
    "dysmenorrhea", "amenorrhea", "polycystic ovary syndrome", "vaginitis",
    "vulvodynia", "candidiasis", "trichomoniasis", "bacterial vaginosis",
    "genital herpes", "human papillomavirus", "syphilis", "gonorrhea", "chlamydia",
    "hiv/aids", "hepatitis a", "hepatitis b", "hepatitis c", "hepatitis d",
    "hepatitis e", "yellow fever", "zika virus", "chikungunya", "ebola virus",
    "marburg virus", "lassa fever", "rabies", "leptospirosis", "brucellosis",
    "q fever", "rocky mountain spotted fever", "lyme disease", "anaplasmosis",
    "ehrlichiosis", "babesiosis", "toxoplasmosis", "malaria", "leishmaniasis",
    "trypanosomiasis", "schistosomiasis", "filariasis", "onchocerciasis",
    "dracunculiasis", "ascariasis", "trichuriasis", "hookworm infection",
    "strongyloidiasis", "taeniasis", "cysticercosis", "echinococcosis",
    "clonorchiasis", "opisthorchiasis", "paragonimiasis", "fascioliasis",
    "giardiasis", "cryptosporidiosis", "cyclosporiasis", "microsporidiosis",
    "amoebiasis", "naegleria fowleri infection", "acanthamoeba keratitis",
    "blastomycosis", "histoplasmosis", "coccidioidomycosis", "paracoccidioidomycosis",
    "sporotrichosis", "aspergillosis", "candidiasis", "cryptococcosis",
    "mucormycosis", "pneumocystis pneumonia", "tuberculosis", "leprosy",
    "actinomycosis", "nocardiosis", "mycetoma", "chromoblastomycosis",
    "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis", "dermatophytosis",
    "tinea versicolor", "tinea pedis", "tinea cruris", "tinea corporis",
    "tinea capitis", "tinea unguium", "tinea barbae", "tinea manuum",
    "tinea faciei", "tinea imbricata", "tinea nigra", "piedra", "sporotrichosis",
    "chromoblastomycosis", "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis",
    "zygomycosis", "dermatophytosis", "tinea versicolor", "tinea pedis",
    "tinea cruris", "tinea corporis", "tinea capitis", "tinea unguium",
    "tinea barbae", "tinea manuum", "tinea faciei", "tinea imbricata",
    "tinea nigra", "piedra", "sporotrichosis", "chromoblastomycosis",
    "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis",
    "dermatophytosis", "tinea versicolor", "tinea pedis", "tinea cruris",
    "tinea corporis", "tinea capitis", "tinea unguium", "tinea barbae",
    "tinea manuum", "tinea faciei", "tinea imbricata", "tinea nigra",
    "piedra", "sporotrichosis", "chromoblastomycosis", "mycetoma",
    "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis", "dermatophytosis",
    "tinea versicolor", "tinea pedis", "tinea cruris", "tinea corporis",
    "tinea capitis", "tinea unguium", "tinea barbae", "tinea manuum",
    "tinea faciei", "tinea imbricata", "tinea nigra", "piedra", "sporotrichosis",
    "chromoblastomycosis", "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis",
    "zygomycosis", "dermatophytosis", "tinea versicolor", "tinea pedis",
    "tinea cruris", "tinea corporis", "tinea capitis", "tinea unguium",
    "tinea barbae", "tinea manuum", "tinea faciei", "tinea imbricata",
    "tinea nigra", "piedra", "sporotrichosis", "chromoblastomycosis",
    "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis",
    "dermatophytosis", "tinea versicolor", "tinea pedis", "tinea cruris",
    "tinea corporis", "tinea capitis", "tinea unguium", "tinea barbae",
    "tinea manuum", "tinea faciei", "tinea imbricata", "tinea nigra",
    "piedra", "sporotrichosis", "chromoblastomycosis", "mycetoma",
    "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis", "dermatophytosis",
    "tinea versicolor", "tinea pedis", "tinea cruris", "tinea corporis",
    "tinea capitis", "tinea unguium", "tinea barbae", "tinea manuum",
    "tinea faciei", "tinea imbricata", "tinea nigra", "piedra", "sporotrichosis",
    "chromoblastomycosis", "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis",
    "zygomycosis", "dermatophytosis", "tinea versicolor", "tinea pedis",
    "tinea cruris", "tinea corporis", "tinea capitis", "tinea unguium",
    "tinea barbae", "tinea manuum", "tinea faciei", "tinea imbricata",
    "tinea nigra", "piedra", "sporotrichosis", "chromoblastomycosis",
    "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis",
    "dermatophytosis", "tinea versicolor", "tinea pedis", "tinea cruris",
    "tinea corporis", "tinea capitis", "tinea unguium", "tinea barbae",
    "tinea manuum", "tinea faciei", "tinea imbricata", "tinea nigra",
    "piedra", "sporotrichosis", "chromoblastomycosis", "mycetoma",
    "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis", "dermatophytosis",
    "tinea versicolor", "tinea pedis", "tinea cruris", "tinea corporis",
    "tinea capitis", "tinea unguium", "tinea barbae", "tinea manuum",
    "tinea faciei", "tinea imbricata", "tinea nigra", "piedra", "sporotrichosis",
    "chromoblastomycosis", "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis",
    "zygomycosis", "dermatophytosis", "tinea versicolor", "tinea pedis",
    "tinea cruris", "tinea corporis", "tinea capitis", "tinea unguium",
    "tinea barbae", "tinea manuum", "tinea faciei", "tinea imbricata",
    "tinea nigra", "piedra", "sporotrichosis", "chromoblastomycosis",
    "mycetoma", "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis",
    "dermatophytosis", "tinea versicolor", "tinea pedis", "tinea cruris",
    "tinea corporis", "tinea capitis", "tinea unguium", "tinea barbae",
    "tinea manuum", "tinea faciei", "tinea imbricata", "tinea nigra",
    "piedra", "sporotrichosis", "chromoblastomycosis", "mycetoma",
    "phaeohyphomycosis", "hyalohyphomycosis", "zygomycosis", "dermatophytosis",
    "tinea versicolor", "tinea pedis", "tinea cruris", "tinea corporis",
    "tinea capitis", "tinea unguium", "tinea barbae", "tinea manuum",
    "tinea faciei", "tinea imbricata", "tinea nigra", "piedra", "sporotrichosis"
];