const symptoms = [
  "headache", "fever", "cough", "sore throat", "fatigue", "nausea", "vomiting", "dizziness",
  "chills", "muscle pain", "joint pain", "runny nose", "shortness of breath", "loss of taste",
  "loss of smell", "abdominal pain", "diarrhea", "constipation", "back pain", "chest pain",
  "rash", "itching", "blurred vision", "insomnia", "sweating", "palpitations", "weight loss",
  "weight gain", "swelling", "skin redness", "anxiety", "depression", "tremors", "weakness",
  "dry mouth", "ear pain", "eye pain", "sneezing", "hoarseness", "memory loss", "seizures",
  "difficulty swallowing", "cold hands", "cold feet", "frequent urination", "painful urination",
  "bruising", "hair loss", "night sweats", "light sensitivity", "hearing loss", "acne", "agitation",
  "allergies", "amenorrhea", "amnesia", "angina", "anorexia", "aphasia", "apnea", "arrhythmia",
  "arthralgia", "asthma", "ataxia", "auditory hallucinations", "autoimmune symptoms", "belching",
  "bleeding gums", "bloating", "blurred speech", "bone pain", "bowel incontinence", "bradycardia",
  "breast pain", "bruising easily", "burning sensation", "calf pain", "chest tightness",
  "chronic cough", "clumsiness", "cognitive impairment", "cold intolerance", "confusion",
  "congestion", "conjunctivitis", "cramping", "cyanosis", "delayed healing", "delirium",
  "dementia", "dermatitis", "diplopia", "disorientation", "dysarthria", "dysesthesia",
  "dysgeusia", "dysmenorrhea", "dyspepsia", "dysphagia", "dysphonia", "dyspnea", "dysuria",
  "ear discharge", "ear fullness", "edema", "epistaxis", "erythema", "esophageal pain",
  "excessive thirst", "facial pain", "facial swelling", "fecal incontinence", "fetal distress",
  "flank pain", "flatulence", "flushing", "focal weakness", "foot pain", "forgetfulness",
  "foul breath", "gait instability", "gas", "general malaise", "goiter", "gout", "groin pain",
  "hallucinations", "halitosis", "hand tremor", "hardened skin", "heat intolerance", "hematemesis",
  "hematochezia", "hematuria", "hemoptysis", "hepatomegaly", "hiccups", "hip pain", "hoarseness",
  "hunger", "hyperpigmentation", "hypersomnia", "hypotension", "impotence", "incontinence",
  "indigestion", "infertility", "inflammation", "inguinal pain", "irritability", "itchy scalp",
  "jaw pain", "jaundice", "joint stiffness", "knee pain", "lacrimation", "laryngitis",
  "leg cramps", "lethargy", "lightheadedness", "lip swelling", "lockjaw", "low libido",
  "low-grade fever", "lymphadenopathy", "malnutrition", "malaise", "memory problems",
  "menstrual irregularities", "migraine", "mouth ulcers", "muscle cramps", "muscle twitching",
  "myalgia", "nasal discharge", "nasal obstruction", "nausea on exertion", "neck stiffness",
  "neuralgia", "nipple discharge", "nocturia", "nosebleeds", "numbness", "obesity", "odynophagia",
  "oliguria", "orthopnea", "otitis", "painful intercourse", "pallor", "panic attacks",
  "paralysis", "paresthesia", "pelvic pain", "peripheral edema", "photophobia", "pleuritic pain",
  "polyuria", "postnasal drip", "pressure in head", "pruritus", "ptosis", "pulmonary edema",
  "purpura", "rashes", "rectal bleeding", "restless legs", "retinal detachment", "rigidity",
  "scalp tenderness", "sciatica", "scoliosis", "seasonal allergies", "sensory loss",
  "sinus pressure", "skin peeling", "skin thickening", "skin ulcer", "slurred speech",
  "snoring", "sore gums", "spasms", "splenomegaly", "spontaneous bleeding", "stiff neck",
  "stomach cramps", "strabismus", "stridor", "stroke symptoms", "stuttering", "subcutaneous nodules",
  "sudden weakness", "syncope", "tachycardia", "tender abdomen", "testicular pain", "tinnitus",
  "toe pain", "tongue swelling", "toothache", "tremor", "trismus", "unexplained bruising",
  "urethral discharge", "urinary incontinence", "urinary retention", "urinary urgency",
  "varicose veins", "vertigo", "vision loss", "visual auras", "vomiting blood", "wheezing",
  "wrinkled skin", "wrist pain", "yellow skin", "yawning excessively", "zinging pain",
  "abdominal bloating", "abnormal gait", "abnormal reflexes", "abnormal taste", "abnormal vision",
  "absent reflexes", "aching muscles", "aching joints", "acid reflux", "acneiform rash", "acrocyanosis",
  "acute pain", "adnexal tenderness", "adrenal insufficiency", "aggressive behavior", "air hunger",
  "alopecia", "altered mental status", "anal fissure", "anal itching", "anal pain", "anemia",
  "ankle pain", "ankle swelling", "anterior uveitis", "aphthous ulcers", "apraxia", "arm pain",
  "arm weakness", "arterial insufficiency", "arthropathy", "ascites", "asymmetric facies",
  "ataxic gait", "atrophy", "auditory loss", "aura", "autoimmune hemolysis", "axillary mass",
  "axillary pain", "back stiffness", "balance problems", "bald patches", "bedwetting", "behavioral changes",
  "belly pain", "biliary colic", "black stools", "blackouts", "bladder pain", "bleeding diathesis",
  "blepharospasm", "blind spot", "blindness", "blisters", "blood in stool", "blood in urine",
  "bloodshot eyes", "blue lips", "blue skin", "body aches", "bone deformity", "bone tenderness",
  "bony overgrowth", "bradyphrenia", "brain fog", "breast lump", "breast swelling", "breath odor",
  "breath sounds", "breathlessness", "brittle nails", "bronchitis", "bruxism", "bulging eyes",
  "bullae", "burning feet", "burning mouth", "burning tongue", "bursitis", "cachexia", "café au lait spots",
  "calf swelling", "candidiasis", "canker sores", "capillary refill", "cardiac arrhythmia", "cardiac murmur",
  "cardiomegaly", "carpal tunnel", "cataplexy", "cataracts", "cavernous sinus thrombosis", "cellulitis",
  "central cyanosis", "cerebellar ataxia", "cerebral edema", "cervical lymphadenopathy", "cervical pain",
  "cervical spine pain", "chapped lips", "cheilitis", "chest discomfort", "chest expansion", "chest wall pain",
  "choking", "chorea", "chronic fatigue", "chronic pain", "claudication", "claw hand", "clubbing",
  "coarse hair", "coarse skin", "cognitive decline", "cold sores", "colic", "colitis", "coma",
  "compartment syndrome", "compulsive behavior", "concentration problems", "confabulation", "congenital defects",
  "congestive heart failure", "conjunctival injection", "constricted pupils", "convulsions", "copd",
  "corneal abrasion", "corneal ulcer", "costochondritis", "coughing up blood", "cracked lips",
  "cracked skin", "cramps", "cranial nerve palsy", "crepitus", "croup", "crying spells", "cushingoid appearance",
  "cutaneous nodules", "cyanotic", "cystitis", "dactylitis", "deafness", "decreased appetite", "decreased libido",
  "decreased reflexes", "decreased sweating", "deep vein thrombosis", "deformity", "dehydration", "delayed puberty",
  "delusions", "dental pain", "depressed mood", "dermal sinus", "dermatographia", "developmental delay",
  "diabetes insipidus", "diabetic ketoacidosis", "diaphoresis", "difficulty concentrating", "difficulty walking",
  "digital clubbing", "diplopia", "discharge", "discomfort", "disorganized speech", "distended abdomen",
  "distended veins", "distractibility", "diverticulitis", "dizziness on standing", "double vision",
  "drooling", "drooping eyelid", "dry eyes", "dry skin", "dullness", "dyschezia", "dyspareunia",
  "dysphoria", "dysplasia", "dyspnea on exertion", "dystonia", "ear pressure", "earache", "early satiety",
  "easy bruising", "eating disorders", "echolalia", "ectropion", "eczema", "edema of legs", "effusion",
  "elbow pain", "emotional lability", "emphysema", "encephalopathy", "endometriosis", "enlarged liver",
  "enlarged spleen", "enteritis", "entropion", "enuresis", "eosinophilia", "epididymitis", "epigastric pain",
  "epiphora", "episcleritis", "erectile dysfunction", "erosion", "erythema multiforme", "erythema nodosum",
  "esophageal dysmotility", "esophageal spasm", "esophageal varices", "eustachian tube dysfunction",
  "excessive salivation", "excessive urination", "excoriation", "exercise intolerance", "exophthalmos",
  "expressive aphasia", "extensor plantar response", "extrapyramidal symptoms", "extreme fatigue",
  "eye discharge", "eye floaters", "eye irritation", "eye redness", "eyelid swelling", "facial asymmetry",
  "facial droop", "facial numbness", "facial paralysis", "facial tics", "failure to thrive", "fainting",
  "falling", "false beliefs", "fasciculations", "fatigue on exertion", "febrile seizures", "feeding difficulties",
  "fever blisters", "fever of unknown origin", "fibromyalgia", "finger pain", "finger swelling", "fissured tongue",
  "flaccid paralysis", "flank tenderness", "flat affect", "flatulence", "flu-like symptoms", "focal seizures",
  "folliculitis", "food intolerance", "foot drop", "foot numbness", "foot swelling", "forehead pain",
  "foreign body sensation", "fracture", "frequent infections", "frequent stools", "frontal headache",
  "frozen shoulder", "fungal infection", "gagging", "gait disturbance", "gallop rhythm", "gangrene",
  "gastric pain", "gastroenteritis", "gastroesophageal reflux", "gastrointestinal bleeding", "genital lesions",
  "genital pain", "genital ulcers", "geographic tongue", "gestational diabetes", "giant cell arteritis",
  "gingival bleeding", "gingival hyperplasia", "gingivitis", "glaucoma", "glomerulonephritis", "glossitis",
  "glossodynia", "glucose intolerance", "glycosuria", "goosebumps", "gouty arthritis", "granuloma",
  "graves disease", "grief", "groin swelling", "gross hematuria", "growth delay", "growth failure",
  "guillain-barre syndrome", "gum bleeding", "gum pain", "gum swelling", "gynecomastia", "hair thinning",
  "hallux valgus", "hammer toe", "hand pain", "hand swelling", "hard stools", "head injury", "head thrust",
  "hearing impairment", "heart block", "heartburn", "heat rash", "heavy legs", "heel pain", "hemangioma",
  "hemianopia", "hemiparesis", "hemiplegia", "hemolysis", "hemorrhoids", "hepatic encephalopathy",
  "hepatic failure", "hepatitis", "hepatosplenomegaly", "hernia", "herpes", "hiccoughs", "high arches",
  "hirsutism", "hives", "hoarse voice", "homonymous hemianopia", "hot flashes", "hunger pains", "hydrocele",
  "hydrocephalus", "hyperactivity", "hypercalcemia", "hypercapnia", "hyperglycemia", "hyperhidrosis",
  "hyperkalemia", "hyperkinesis", "hyperlipidemia", "hypernatremia", "hyperreflexia", "hypersalivation",
  "hypersensitivity", "hypertension", "hyperthermia", "hyperthyroidism", "hypertriglyceridemia",
  "hypertrophy", "hyperventilation", "hypoalbuminemia", "hypocalcemia", "hypochondriasis", "hypogeusia",
  "hypoglycemia", "hypogonadism", "hypokalemia", "hypomagnesemia", "hypomania", "hyponatremia",
  "hypophonia", "hypoproteinemia", "hyporeflexia", "hypotension", "hypothermia", "hypothyroidism",
  "hypotonia", "hypoventilation", "hypovolemia", "hypoxemia", "hypoxia", "hysteria", "ichthyosis",
  "icterus", "idiopathic", "ileus", "impaired balance", "impaired coordination", "impaired hearing",
  "impaired memory", "impaired smell", "impaired taste", "impaired vision", "impulsivity", "inability to urinate",
  "incoordination", "increased appetite", "increased reflexes", "increased thirst", "increased urination",
  "induration", "infantile spasms", "infection", "infertility", "inflammatory bowel disease", "influenza",
  "inguinal hernia", "inhalation injury", "insect bites", "insomnia", "intermittent claudication",
  "interstitial lung disease", "intestinal obstruction", "intracranial pressure", "intrauterine growth restriction",
  "intussusception", "irregular heartbeat", "irregular menstruation", "irritability", "ischemia",
  "itching", "jaundice", "joint deformity", "joint effusion", "joint instability", "joint locking",
  "joint swelling", "keratitis", "keratosis", "kernicterus", "kidney pain", "knee effusion", "knee instability",
  "knee locking", "kyphosis", "labyrinthitis", "laceration", "lactose intolerance", "lagophthalmos",
  "large hands", "large head", "large tongue", "laryngeal edema", "laryngospasm", "lazy eye", "left arm pain",
  "left leg pain", "leg weakness", "lethargy", "leukocytosis", "leukopenia", "lichenification", "limb pain",
  "limb weakness", "lipodystrophy", "liver failure", "liver tenderness", "localized pain", "locked knee",
  "long face", "loss of appetite", "loss of balance", "loss of consciousness", "loss of coordination",
  "loss of hair", "loss of sensation", "low back pain", "low blood pressure", "low energy", "low platelet count",
  "low white blood cell count", "lower abdominal pain", "lumbar pain", "lump in breast", "lump in groin",
  "lump in neck", "lump in throat", "lung consolidation", "lymphadenitis", "lymphangitis", "lymphedema",
  "lymphocytosis", "lymphopenia", "macrocytosis", "macroglossia", "macules", "malaise", "malar rash",
  "male pattern baldness", "malocclusion", "mammary pain", "mandibular pain", "mania", "marfanoid habitus",
  "mastalgia", "mastitis", "mastoiditis", "maxillary pain", "meconium", "medial epicondylitis", "megaloblastic anemia",
  "melena", "memory impairment", "meniere's disease", "meningismus", "meningitis", "menorrhagia", "mental retardation",
  "metabolic acidosis", "metatarsalgia", "microcephaly", "microcytosis", "micrognathia", "migraine with aura",
  "miosis", "mitral regurgitation", "mitral stenosis", "molluscum contagiosum", "monoarthritis", "monoclonal gammopathy",
  "mononeuritis multiplex", "mononucleosis", "mood swings", "morning sickness", "morton's neuroma", "motor tics"];